### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ModMike** [akaJes/marlin-config#51]
I am trying to help someone install the configurator on a Windows 10 machine.  We used the panel to install Github and PIO but every time we go to restart, it says uninstalled.

Now we are getting:

javascript error has occurred in the main process uncaught exception: type header cannot read property headers

**Comment by akaJes** [comment]
Which version installed and what kind of error? If possible leave some
screenshots

Вт, 10 лип. 2018, 20:57 користувач Michael Triffon <notifications@github.com>
пише:

**Comment by ModMike** [comment]
It was the latest version and I don't have screen shots.  The installer is completely broken, we had to install each piece manually.  You also say the PIO is optional when it clearly is NOT.  You need PIO to compile.

**Comment by akaJes** [comment]
PIO is optional because the main feature of this app to configure headers
of your firmware. To compile the firmware is possible with your preferred
GUI like Arduino, atom or other. PIO is huge project and works better with
Linux like os and not included to this app. Also you can install it
manually from the official website

Вт, 17 лип. 2018, 18:52 користувач Michael Triffon <notifications@github.com>
пише:
